image: maven:3.6.3-jdk-11

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  tags:
    - hva
  script:
    - mvn package -Dmaven.test.skip=true

unit-test-job:
  stage: test
  tags:
    - hva
  script:
    - mvn test

lint-test-job:
  stage: test
  tags:
    - hva
  script:
    - your-lint-command-here

deploy-job:
  stage: deploy
  tags:
    - hva
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_PRODUCTION_KEY
  only:
    - master
